Repository ovh-ux/ovh-module-exchange, pull requests merged in 2018-02, with the labels that each got.

#35 SPF/DKIM configuration changes now updates all accounts retroactively
  src/exchange/configure/service-configure.controller.js
  src/exchange/exchange.service.js
  src/resources/i18n/exchange/Messages_fr_FR.xml
Labels: quality check ok

#76 fix(wizard): IE11 compatibility
  src/exchange/wizard-hosted-creation/first-step/domain-configuration/domain-configuration.component.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/add/add.controller.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/delete/delete.controller.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.component.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/update/update.controller.js
  src/exchange/wizard-hosted-creation/first-step/header/header.component.js
  src/exchange/wizard-hosted-creation/summary/automatic/automatic.controller.js
  src/exchange/wizard-hosted-creation/summary/manual/manual.controller.js
  src/exchange/wizard-hosted-creation/summary/summary.component.js
  src/exchange/wizard-hosted-creation/wizard-hosted-creation.component.js
Labels: bug, quality check ok

#77 Hotfix/wizard authoritative email pro
  src/exchange/services/exchange.messaging.service.js
  src/exchange/wizard-hosted-creation/first-step/domain-configuration/domain-configuration.component.js
  src/exchange/wizard-hosted-creation/wizard-hosted-creation.html
  src/resources/i18n/exchange/Messages_fr_FR.xml
Labels: bug, quality check ok

#80 fix(account/order): add configureme.me account message
  src/exchange/account/account.controller.js
  src/exchange/account/order/account-order.controller.js
  src/exchange/account/order/account-order.html
  src/resources/i18n/exchange/Messages_fr_FR.xml
Labels: bug, quality check ok

#88 fix(page-header): restrict orders URLs from some targets.
  package-lock.json
  src/exchange/exchange.controller.js
  src/exchange/exchange.html
Labels: bug

#83 Feature/oui datagrid (uu-627)
  src/exchange/account/alias/account-alias.controller.js
  src/exchange/account/alias/account-alias.html
  src/exchange/group/alias/group-alias.controller.js
  src/exchange/group/alias/group-alias.html
  src/exchange/group/manager/group-manager.controller.js
  src/exchange/group/manager/group-manager.html
  src/exchange/group/member/group-member.controller.js
  src/exchange/group/member/group-member.html
Labels: quality check ok

#89 fix(information): restrict office attached from some targets.
  src/exchange/information/information.controller.js
  src/exchange/information/information.html
Labels: bug

#87 hotfix/wizard email creation
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.component.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.html
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.service.js
  src/exchange/wizard-hosted-creation/summary/summary.component.js
Labels: bug, quality check ok

#86 fix(office-attach): header displays again
  src/exchange/account/account.controller.js
  src/exchange/account/account.html
  src/exchange/exchange.controller.js
  src/exchange/exchange.html
  src/exchange/information/information.html
  src/exchange/office-attach/dialog/office-attach-dialog.controller.js
  src/exchange/office-attach/dialog/office-attach-dialog.html
  src/exchange/office-attach/office-attach.directive.js
  src/exchange/office-attach/office-attach.html
  src/exchange/office-attach/office-attach.service.js
  src/exchange/office-attached/office-attached.directive.js
  src/exchange/office-attached/office-attached.html
  src/exchange/office-attached/office-attached.service.js
Labels: bug, quality check ok

#84 Feature/oui datagrid distclaimer and task
  src/exchange/disclaimer/add/disclaimer-add.controller.js
  src/exchange/disclaimer/disclaimer.controller.js
  src/exchange/disclaimer/disclaimer.html
  src/exchange/disclaimer/popover/disclaimer.popover.controller.js
  src/exchange/disclaimer/popover/disclaimer.popover.html
  src/exchange/task/task.controller.js
  src/exchange/task/task.html
Labels: quality check ok

#65 Chore/fix French translation
  src/resources/i18n/exchange/Messages_fr_FR.xml
Labels: bug, quality check ok
