Repository ovh-ux/ovh-module-exchange, pull requests merged in 2018-11, with the labels that each got.

#187 refactor(*): remove reference to deprecated offer
  src/exchange/account/account.service.js
  src/exchange/account/home/account-home.html
  src/exchange/account/update/account-update.controller.js
  src/exchange/account/update/account-update.html
  src/exchange/exchange.html
  src/exchange/exchange.tabs.controller.js
  src/exchange/header/update-renew/update-renew.controller.js
  src/exchange/information/information.html
  src/exchange/services/exchange.serviceInfrastucture.service.js
  src/exchange/services/exchange.version.service.js
  src/exchange/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#190 fix(i18n): retrieve translations
  src/exchange/translations/Messages_de_DE.xml
  src/exchange/translations/Messages_en_CA.xml
  src/exchange/translations/Messages_en_US.xml
  src/exchange/translations/Messages_es_US.xml
  src/exchange/translations/Messages_it_IT.xml
  src/exchange/translations/Messages_nl_NL.xml
  src/exchange/translations/Messages_pt_PT.xml
Labels: bug

#188 Fix/wizard
  src/exchange/exchange.controller.js
  src/exchange/exchange.html
  src/exchange/exchange.module.js
  src/exchange/exchange.routes.js
  src/exchange/header/header.component.js
  src/exchange/header/header.html
  src/exchange/header/header.service.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.component.js
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.html
  src/exchange/wizard-hosted-creation/first-step/email-creation/email-creation.service.js
  src/exchange/wizard-hosted-creation/summary/summary.component.js
  src/exchange/wizard-hosted-creation/wizard-hosted-creation.component.js
  src/exchange/wizard-hosted-creation/wizard-hosted-creation.html
Labels: bug, quality check ok

#181 refactor(exchange.information): use oui-tile component
  src/exchange/information/information.controller.js
  src/exchange/information/information.html
Labels: enhancement, quality check ok

#202 Update readme
  README.md
Labels: enhancement

#206 fix(renew): fix automatic opening of renew modal
  src/exchange/exchange.controller.js
Labels: bug, quality check ok

#204 Feat/export csv exchange
  src/exchange/account/export-as-csv/account-export-as-csv.controller.js
  src/exchange/account/home/account-home.html
  src/exchange/exchange.service.js
  src/exchange/external-contact/external-contact.html
  src/exchange/external-contact/external-contact.service.js
  src/exchange/group/group.html
  src/exchange/shared-account/shared-account.html
  src/exchange/shared-account/shared-account.service.js
  src/exchange/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#194 fix(shared-account): adapt maximum quota unit
  .eslintrc.json
  package.json
  src/exchange/shared-account/add/shared-account-add.controller.js
  src/exchange/shared-account/add/shared-account-add.html
  src/exchange/shared-account/shared-account.html
  src/exchange/shared-account/shared-account.service.js
  src/exchange/shared-account/update/shared-account-update.controller.js
  src/exchange/shared-account/update/shared-account-update.html
  src/exchange/translations/Messages_fr_FR.xml
  yarn.lock
Labels: bug, quality check ok, translation required

#209 feat(resiliation): allow to open resiliation modal with url param
  src/exchange/exchange.controller.js
Labels: enhancement, quality check ok

#183 refactor(components.api): use api from wuc
  src/exchange/exchange.api.js
Labels: :santa: one-manager, quality check ok

#205 fix(products): remove use of Products service
  package.json
  src/exchange/domain/domain.service.js
  src/exchange/exchange.service.js
  src/exchange/order/order.controller.js
  src/exchange/resource/resource.service.js
  src/exchange/shared/shared.service.js
  yarn.lock
Labels: :santa: one-manager, quality check ok

#184 refactor(components.string): move to webUniverseComponents
  src/exchange/account/alias/add/account-alias-add.html
  src/exchange/account/alias/remove/account-alias-remove.html
  src/exchange/account/outlook/activate/account-outlook-activate.html
  src/exchange/account/remove/account-remove.html
  src/exchange/account/update/account-update.html
  src/exchange/disclaimer/disclaimer.html
  src/exchange/disclaimer/remove/disclaimer-remove.html
  src/exchange/domain/add/domain-add.html
  src/exchange/domain/domain.html
  src/exchange/domain/mx-autoconfig/domain-mx-autoconfig.html
  src/exchange/domain/remove/domain-remove.html
  src/exchange/domain/srv-autoconfig/domain-srv-autoconfig.html
  src/exchange/domain/update/domain-update.html
  src/exchange/external-contact/add/external-contact-add.html
  src/exchange/external-contact/external-contact.html
  src/exchange/external-contact/remove/external-contact-remove.html
  src/exchange/external-contact/update/external-contact-update.html
  src/exchange/group/accounts/group-accounts.html
  src/exchange/group/add/group-add.html
  src/exchange/group/alias/add/group-alias-add.html
  src/exchange/group/alias/remove/group-alias-remove.html
  src/exchange/group/group.html
  src/exchange/group/manager/remove/group-manager-remove.html
  src/exchange/group/member/remove/group-member-remove.html
  src/exchange/group/remove/group-remove.html
  src/exchange/group/update/group-update.html
  src/exchange/header/update-renew/update-renew.html
  src/exchange/information/ssl/service-ssl-renew.html
  src/exchange/resource/add/resource-add.html
  src/exchange/resource/remove/resource-remove.html
  src/exchange/resource/resource.html
  src/exchange/resource/update/resource-update.controller.js
  src/exchange/resource/update/resource-update.html
  src/exchange/shared-account/add/shared-account-add.html
  src/exchange/shared-account/delete/shared-account-delete.html
  src/exchange/shared-account/update/shared-account-update.html
  src/exchange/shared/add/shared-add.html
  src/exchange/shared/permission/remove/shared-permission-remove.html
  src/exchange/shared/remove/shared-remove.html
  src/exchange/shared/update/shared-update.html
  src/exchange/wizard-hosted-creation/first-step/email-creation/delete/delete.html
Labels: :santa: one-manager, quality check ok

#182 refactor(components.chartjs): use chartjs from wuc
  src/exchange/header/license/service-license-history.controller.js
  src/exchange/header/license/service-license-history.html
Labels: :santa: one-manager, quality check ok

#189 refactor(components.validator): move to webUniverseComponents
  src/exchange/domain/add/domain-add.controller.js
  src/exchange/domain/update/domain-update.controller.js
Labels: :santa: one-manager, quality check ok

#185 refactor(components.loader): replace loader by oui-spinner
  src/exchange/account/delegation/account-delegation.html
  src/exchange/domain/domain.html
  src/exchange/external-contact/external-contact.html
  src/exchange/group/accounts/group-accounts.html
  src/exchange/group/add/group-add.html
  src/exchange/group/delegation/group-delegation.html
  src/exchange/group/group.html
  src/exchange/header/update-renew/update-renew.html
  src/exchange/office-attach/dialog/office-attach-dialog.html
  src/exchange/resource/delegation/resource-delegation.html
  src/exchange/resource/resource.html
  src/exchange/shared-account/delegation/shared-account-delegation.html
  src/exchange/shared-account/shared-account.html
  src/exchange/shared/permission/shared-permission.html
  src/exchange/shared/permission/update/shared-permission-update.html
  src/exchange/shared/shared.html
Labels: :santa: one-manager, quality check ok

#216 fix(account.office): hide office offer for some subsidiaries
  src/exchange/account/home/account-home.component.js
Labels: bug, quality check ok

#215 fix(missing-status): status missing in task
  src/exchange/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#218 fix(account.office): hide office offer for some subsidiaries
  src/exchange/account/home/account-home.component.js
Labels: bug, quality check ok

#224 fix: replace translation
  src/exchange/translations/Messages_fr_FR.xml
  yarn.lock
Labels: bug, quality check ok

#228 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug

#232 fix(i18n): retrieve translations
  src/exchange/translations/Messages_en_ASIA.xml
  src/exchange/translations/Messages_en_AU.xml
  src/exchange/translations/Messages_en_CA.xml
  src/exchange/translations/Messages_en_GB.xml
  src/exchange/translations/Messages_en_SG.xml
  src/exchange/translations/Messages_en_US.xml
  src/exchange/translations/Messages_es_ES.xml
  src/exchange/translations/Messages_it_IT.xml
  src/exchange/translations/Messages_nl_NL.xml
  src/exchange/translations/Messages_pl_PL.xml
Labels: bug

#223 Feat/group account selection
  src/exchange/group/accounts/group-accounts.controller.js
  src/exchange/group/accounts/group-accounts.html
  src/exchange/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required
