Repository ovh-ux/ovh-module-exchange, pull requests merged in 2018-10, with the labels that each got.

#133 fix: increase csv export limit
  src/exchange/account/export-as-csv/account-export-as-csv.controller.js
Labels: bug, quality check ok

#137 fix(translations): add missing translation
  src/exchange/translations/Messages_fr_FR.xml
Labels: bug

#145 docs(readme): update readme file
  CONTRIBUTING.md
  README.md
Labels: enhancement

#146 fix: remove package-lock.json file
  package-lock.json
Labels: bug

#147 fix: update license file
  LICENSE
Labels: bug

#150 fix: apply eslint rules
  .eslintrc
  package.json
  src/exchange/account/account.controller.js
  src/exchange/account/account.service.js
  src/exchange/account/accountTypes.service.js
  src/exchange/account/add/account-add.controller.js
  src/exchange/account/alias/account-alias.component.js
  src/exchange/account/alias/add/account-alias-add.controller.js
  src/exchange/account/delegation/account-delegation.controller.js
  src/exchange/account/export-as-csv/account-export-as-csv.controller.js
  src/exchange/account/home/account-home.component.js
  src/exchange/account/order/account-order.controller.js
  src/exchange/account/outlook/account-outlook.controller.js
  src/exchange/account/outlook/account-outlook.service.js
  src/exchange/account/update/account-update.controller.js
  src/exchange/components/ckeditor/ckeditor.directive.js
  src/exchange/diagnostic/diagnostic.controller.js
  src/exchange/diagnostic/diagnostic.service.js
  src/exchange/disclaimer/add/disclaimer-add.controller.js
  src/exchange/disclaimer/disclaimer.controller.js
  src/exchange/disclaimer/update/disclaimer-update.controller.js
  src/exchange/domain/add/domain-add.controller.js
  src/exchange/domain/domain.controller.js
  src/exchange/domain/domain.service.js
  src/exchange/exchange.controller.js
  src/exchange/exchange.module.js
  src/exchange/exchange.password.service.js
  src/exchange/exchange.service.js
  src/exchange/external-contact/add/external-contact-add.controller.js
  src/exchange/external-contact/external-contact.service.js
  src/exchange/external-contact/update/external-contact-update.controller.js
  src/exchange/group/add/group-add.controller.js
  src/exchange/group/alias/add/group-alias-add.controller.js
  src/exchange/group/alias/group-alias.controller.js
  src/exchange/group/delegation/group-delegation.controller.js
  src/exchange/group/manager/group-manager.controller.js
  src/exchange/group/member/group-member.controller.js
  src/exchange/group/update/group-update.controller.js
  src/exchange/header/license/service-license-history.service.js
  src/exchange/header/update-renew/update-renew.controller.js
  src/exchange/information/information.controller.js
  src/exchange/office-attach/dialog/office-attach-dialog.controller.js
  src/exchange/office-attach/office-attach.service.js
  src/exchange/order/order.controller.js
  src/exchange/resource/add/resource-add.controller.js
  src/exchange/services/exchange.serviceInfrastucture.service.js
  src/exchange/services/exchange.version.service.js
  src/exchange/shared-account/add/shared-account-add.controller.js
  src/exchange/shared-account/delegation/shared-account-delegation.controller.js
  src/exchange/shared-account/update/shared-account-update.controller.js
  src/exchange/shared/add/shared-add.controller.js
  src/exchange/shared/permission/shared-permission.controller.js
  src/exchange/shared/permission/update/shared-permission-update.controller.js
  src/exchange/shared/update/shared-update.controller.js
  src/exchange/task/task.controller.js
Labels: bug

#152 fix(disclaimer): exclude editor usage for IE11
  src/exchange/components/ckeditor/ckeditor.directive.js
Labels: bug

#155 build(changelog): use npx conventional-changelog-cli with angular preset
  package.json
  yarn.lock
Labels: enhancement

#159 refactor(exchange.information): use oui-component
  src/exchange/information/information.html
Labels: enhancement

#160 refactor(exchange.information): use oui-action-menu
  src/exchange/information/information.html
Labels: enhancement

#165 fix(disclaimer): rollback to ckeditor 4
  package.json
  src/exchange/components/ckeditor/ckeditor.directive.js
  src/exchange/disclaimer/add/disclaimer-add.html
  src/exchange/disclaimer/update/disclaimer-update.html
  src/exchange/exchange.module.js
  yarn.lock
Labels: bug

#175 refactor(eslint): switch to json format as configuration file
  .eslintrc.json
Labels: enhancement

#176 refactor: extract configuration from package.json into json files
  .huskyrc.json
  .lintstagedrc.json
  package.json
Labels: enhancement

#171 refactor(exchange.external.contact): use oui-component
  src/exchange/external-contact/external-contact.controller.js
  src/exchange/external-contact/external-contact.html
  src/exchange/external-contact/popover/external-contact-popover.controller.js
  src/exchange/external-contact/popover/external-contact-popover.html
Labels: enhancement

#173 refactor(exchange.resource): use oui-component
  src/exchange/ExchangeToolboxes.js
  src/exchange/resource/popover/resource.popover.controller.js
  src/exchange/resource/popover/resource.popover.html
  src/exchange/resource/resource.controller.js
  src/exchange/resource/resource.html
Labels: enhancement

#174 refactor(exchange.disclaimer): use oui-status
  src/exchange/disclaimer/disclaimer.html
Labels: enhancement

#120 fix(order): price without tax addition in order step1
  src/exchange/account/order/account-order.controller.js
  src/exchange/account/order/account-order.html
  src/exchange/exchange.service.js
  src/exchange/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#172 refactor(exchange.shared.account): use oui-component
  src/exchange/shared-account/popover/shared-account.popover.controller.js
  src/exchange/shared-account/popover/shared-account.popover.html
  src/exchange/shared-account/shared-account.controller.js
  src/exchange/shared-account/shared-account.html
  src/exchange/shared-account/update/shared-account-update.html
Labels: enhancement

#164 refactor(exchange.domain): use oui-component
  src/exchange/domain/domain.controller.js
  src/exchange/domain/domain.html
  src/exchange/domain/popover/domain.popover.controller.js
  src/exchange/domain/popover/domain.popover.html
Labels: enhancement

#178 build(htmlhint): add htmlhint configuration
  .htmlhintrc
  .lintstagedrc.json
  package.json
  src/exchange/account/export-as-pst/account-export-as-pst.html
  src/exchange/account/order/account-order.html
  src/exchange/configure/service-configure.html
  src/exchange/external-contact/external-contact.controller.js
  yarn.lock
Labels: enhancement

#179 style(package.json): sort entries
  package.json
Labels: enhancement
