Repository ovh-ux/ovh-module-exchange, pull requests merged in 2019-08, with the labels that each got.

#315 fix(i18n): retrieve translations
  src/exchange/translations/Messages_de_DE.xml
  src/exchange/translations/Messages_pl_PL.xml
Labels: bug

#316 build(dev-deps): upgrade some dev dependencies
  package.json
  yarn.lock
Labels: dependencies

#317 Release v9.4.6
  package.json
  src/exchange/translations/Messages_de_DE.xml
  src/exchange/translations/Messages_pl_PL.xml
  yarn.lock
Labels: release :package:

#314 refactor(billing.account-renew): refactor exchange modal to a page
  src/exchange/Exchange.class.js
  src/exchange/billing/account-renew/billing-account-renew.component.js
  src/exchange/billing/account-renew/billing-account-renew.constants.js
  src/exchange/billing/account-renew/billing-account-renew.template.html
  src/exchange/billing/account-renew/renew.component.js
  src/exchange/billing/account-renew/renew.constants.js
  src/exchange/billing/account-renew/renew.controller.js
  src/exchange/billing/account-renew/renew.html
  src/exchange/billing/account-renew/renew.module.js
  src/exchange/billing/account-renew/translations/Messages_fr_FR.xml
  src/exchange/exchange.module.js
  src/exchange/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#321 fix(i18n): retrieve translations
  src/exchange/billing/account-renew/translations/Messages_de_DE.xml
  src/exchange/billing/account-renew/translations/Messages_en_ASIA.xml
  src/exchange/billing/account-renew/translations/Messages_en_AU.xml
  src/exchange/billing/account-renew/translations/Messages_en_CA.xml
  src/exchange/billing/account-renew/translations/Messages_en_GB.xml
  src/exchange/billing/account-renew/translations/Messages_en_SG.xml
  src/exchange/billing/account-renew/translations/Messages_en_US.xml
  src/exchange/billing/account-renew/translations/Messages_es_ES.xml
  src/exchange/billing/account-renew/translations/Messages_it_IT.xml
  src/exchange/billing/account-renew/translations/Messages_pl_PL.xml
  src/exchange/billing/account-renew/translations/Messages_pt_PT.xml
Labels: bug

#322 Release v9.4.7
  src/exchange/Exchange.class.js
  src/exchange/billing/account-renew/billing-account-renew.component.js
  src/exchange/billing/account-renew/billing-account-renew.constants.js
  src/exchange/billing/account-renew/billing-account-renew.template.html
  src/exchange/billing/account-renew/renew.component.js
  src/exchange/billing/account-renew/renew.constants.js
  src/exchange/billing/account-renew/renew.controller.js
  src/exchange/billing/account-renew/renew.html
  src/exchange/billing/account-renew/renew.module.js
  src/exchange/billing/account-renew/translations/Messages_cs_CZ.xml
  src/exchange/billing/account-renew/translations/Messages_de_DE.xml
  src/exchange/billing/account-renew/translations/Messages_en_ASIA.xml
  src/exchange/billing/account-renew/translations/Messages_en_AU.xml
  src/exchange/billing/account-renew/translations/Messages_en_CA.xml
  src/exchange/billing/account-renew/translations/Messages_en_GB.xml
  src/exchange/billing/account-renew/translations/Messages_en_SG.xml
  src/exchange/billing/account-renew/translations/Messages_en_US.xml
  src/exchange/billing/account-renew/translations/Messages_es_ES.xml
  src/exchange/billing/account-renew/translations/Messages_es_US.xml
  src/exchange/billing/account-renew/translations/Messages_fi_FI.xml
  src/exchange/billing/account-renew/translations/Messages_fr_CA.xml
  src/exchange/billing/account-renew/translations/Messages_fr_FR.xml
  src/exchange/billing/account-renew/translations/Messages_it_IT.xml
  src/exchange/billing/account-renew/translations/Messages_lt_LT.xml
  src/exchange/billing/account-renew/translations/Messages_nl_NL.xml
  src/exchange/billing/account-renew/translations/Messages_pl_PL.xml
  src/exchange/billing/account-renew/translations/Messages_pt_PT.xml
  src/exchange/exchange.module.js
  src/exchange/translations/Messages_cs_CZ.xml
  src/exchange/translations/Messages_de_DE.xml
  src/exchange/translations/Messages_en_ASIA.xml
  src/exchange/translations/Messages_en_AU.xml
  src/exchange/translations/Messages_en_CA.xml
  src/exchange/translations/Messages_en_GB.xml
  src/exchange/translations/Messages_en_SG.xml
  src/exchange/translations/Messages_en_US.xml
  src/exchange/translations/Messages_es_ES.xml
  src/exchange/translations/Messages_es_US.xml
  src/exchange/translations/Messages_fi_FI.xml
  src/exchange/translations/Messages_fr_CA.xml
  src/exchange/translations/Messages_fr_FR.xml
  src/exchange/translations/Messages_it_IT.xml
  src/exchange/translations/Messages_lt_LT.xml
  src/exchange/translations/Messages_nl_NL.xml
  src/exchange/translations/Messages_pl_PL.xml
  src/exchange/translations/Messages_pt_PT.xml
Labels: release :package:
